# Generated by Django 4.2.11 on 2025-06-17 14:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=50)),
                ('container_type', models.CharField(choices=[('20DC', '20 قدم عادي'), ('40DC', '40 قدم عادي'), ('20RF', '20 قدم مبرد'), ('40RF', '40 قدم مبرد'), ('TANK', 'صهريج')], max_length=4, verbose_name='نوع الحاوية')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن (طن)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_description', models.TextField(blank=True, verbose_name='وصف المحتويات')),
                ('status', models.CharField(choices=[('LOADING', 'تحميل'), ('EMPTY', 'فارغ'), ('GENERAL_CARGO', 'بضائع عامة'), ('UNLOADING', 'تجزئة')], default='LOADING', max_length=20, verbose_name='الحالة')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='الحجم')),
            ],
            options={
                'verbose_name': 'الحاوية',
                'verbose_name_plural': 'الحاويات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإذن')),
                ('issue_date', models.DateTimeField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('LOADING', 'تحميل'), ('EMPTY', 'فارغ'), ('GENERAL_CARGO', 'بضائع عامة'), ('UNLOADING', 'تجزئة')], default='LOADING', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إذن التسليم',
                'verbose_name_plural': 'أذونات التسليم',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السائق')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقم', regex='^\\d{11}$')], verbose_name='رقم الهاتف')),
                ('mother_name', models.CharField(max_length=100, verbose_name='اسم الأم')),
                ('governorate', models.CharField(choices=[('BGD', 'بغداد'), ('BSR', 'البصرة'), ('NBL', 'بابل'), ('KRB', 'كربلاء'), ('NJF', 'النجف')], max_length=3, verbose_name='المحافظة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الرخصة')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'السائق',
                'verbose_name_plural': 'السائقين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم السائق')),
                ('truck_plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم لوحة الشاحنة')),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'رحلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='المعرف')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('governorate', models.CharField(choices=[('BGD', 'بغداد'), ('NNW', 'نينوى'), ('BSR', 'البصرة'), ('SLY', 'السليمانية'), ('ARB', 'أربيل'), ('THQ', 'ذي قار'), ('NBL', 'بابل'), ('ANB', 'الأنبار'), ('DIY', 'ديالى'), ('KRK', 'كركوك'), ('NJF', 'النجف'), ('WST', 'واسط'), ('QDS', 'القادسية'), ('SLH', 'صلاح الدين'), ('KRB', 'كربلاء'), ('MSN', 'ميسان'), ('DHK', 'دهوك'), ('MTH', 'المثنى')], max_length=50, verbose_name='المحافظة')),
                ('truck_type', models.CharField(choices=[('FLAT', 'مسطحة'), ('CONT', 'حاويات'), ('TANK', 'صهريج')], max_length=50, verbose_name='نوع الشاحنة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شاحنة',
                'verbose_name_plural': 'الشاحنات',
                'ordering': ['-created_at'],
            },
        ),
    ]
