# Generated by Django 4.2.11 on 2025-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='container_size',
            field=models.CharField(choices=[('20DC', '20 قدم عادي'), ('40DC', '40 قدم عادي'), ('20RF', '20 قدم مبرد'), ('40RF', '40 قدم مبرد'), ('TANK', 'صهريج')], default='40DC', help_text='حجم الحاويات الافتراضي لهذا الإذن', max_length=4, verbose_name='حجم الحاويات'),
        ),
    ]
