# Generated by Django 4.2.11 on 2025-06-19 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('DELIVERY', 'مندوب'), ('SUPERVISOR', 'مشرف'), ('MANAGER', 'مدير')], max_length=20, verbose_name='نوع المستخدم')),
                ('is_subscription_active', models.BooleanField(default=False, verbose_name='الاشتراك مفعل')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('plan_type', models.CharField(choices=[('trial', 'تجريبي - 7 أيام'), ('basic', 'أساسي'), ('premium', 'مميز'), ('enterprise', 'مؤسسي')], max_length=20, unique=True, verbose_name='نوع الخطة')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري (دينار)')),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر السنوي (دينار)')),
                ('max_containers', models.IntegerField(verbose_name='الحد الأقصى للحاويات')),
                ('max_trucks', models.IntegerField(verbose_name='الحد الأقصى للشاحنات')),
                ('max_drivers', models.IntegerField(verbose_name='الحد الأقصى للسائقين')),
                ('max_trips_per_month', models.IntegerField(verbose_name='الحد الأقصى للرحلات شهرياً')),
                ('has_financial_reports', models.BooleanField(default=False, verbose_name='التقارير المالية')),
                ('has_advanced_analytics', models.BooleanField(default=False, verbose_name='التحليلات المتقدمة')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='الوصول للـ API')),
                ('has_export_features', models.BooleanField(default=False, verbose_name='ميزات التصدير')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='الدعم الفني المتقدم')),
                ('description', models.TextField(verbose_name='وصف الخطة')),
                ('features_list', models.JSONField(default=list, verbose_name='قائمة الميزات')),
                ('is_active', models.BooleanField(default=True, verbose_name='خطة نشطة')),
                ('is_popular', models.BooleanField(default=False, verbose_name='خطة شائعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], max_length=10, verbose_name='دورة الفوترة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='التجديد التلقائي')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('suspended', 'معلق'), ('trial', 'تجريبي')], default='trial', max_length=20, verbose_name='حالة الاشتراك')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('containers_used', models.IntegerField(default=0, verbose_name='الحاويات المستخدمة')),
                ('trucks_used', models.IntegerField(default=0, verbose_name='الشاحنات المستخدمة')),
                ('drivers_used', models.IntegerField(default=0, verbose_name='السائقين المستخدمين')),
                ('trips_this_month', models.IntegerField(default=0, verbose_name='الرحلات هذا الشهر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscriptionplan', verbose_name='خطة الاشتراك')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اشتراك المستخدم',
                'verbose_name_plural': 'اشتراكات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ بداية الاشتراك')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ نهاية الاشتراك')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
    ]
